name: CI
on:
  push:
    branches:
      - "main"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Build release
        run: make release
            - name: Upload math result for job 1
      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: tarball
          path: zig-out/bin/waycwd*.tar.gz
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set version
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: tarball
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: waycwd ${{ env.VERSION }}
          files: zig-out/bin/waycwd*.tar.gz
          draft: true
