name: CI
on:
  push:
    branches:
      - "main"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Build release
        run: make release
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Extract version
        id: extract_version
        run: echo "::set-output name=version::${{ github.ref#v }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: waycwd ${{ steps.extract_version.outputs.version }}
          files: zig-out/bin/waycwd*.tar.gz
          draft: true
